adding tools to remove packages and cleanup

diff --git a/sabayon-createrepo-cleanup b/sabayon-createrepo-cleanup
--- a/sabayon-createrepo-cleanup
+++ b/sabayon-createrepo-cleanup
@@ -22,41 +22,32 @@ docker_volumes=(
             -v "$OUTPUT_DIR:/sabayon/artifacts"
             -v "$createrepo:/sabayon/bin/create_repo.sh"
             -v "$entropysrv:/etc/entropy/server.conf"
-)
+            -v "$PORTAGE_ARTIFACTS:/usr/portage/packages" )
 
-if [ $# -eq 0 ]
-then
- docker_volumes+=(-v "$PORTAGE_ARTIFACTS:/usr/portage/packages" )
- else
- echo "Packages directory: ${args[0]}"
- docker_volumes+=(-v "${args[0]}:/usr/portage/packages" )
-fi
 
 check_docker_requirements
 
 echo "Repository: $REPOSITORY_NAME"
 echo "Repository Description: $REPOSITORY_DESCRIPTION"
-
+echo "Remove: ${args[@]}"
 
 # Creating the building script on-the-fly
 cat >$createrepo <<EOF
 #!/bin/bash
 set -e
-built_pkgs=\$(find /usr/portage/packages -name "*.tbz2" | xargs)
 repo="\${REPOSITORY:-default}"
-mkdir -p /sabayon/artifacts
-
-[[ -z "\${built_pkgs}" ]] && echo "ERROR: no tbz2s found" && exit 2
 
 if [ -d "/sabayon/artifacts/standard" ]; then
   eit unlock \$repo || true
   eit pull --quick $repo || true
   #eit sync \$repo
 else
-  echo "Yes" | eit init --quick \$repo
+  echo "ouch no repository there" && exit 3;
 fi
 
-echo "Yes" | eit inject \${built_pkgs} || { echo "ouch unable to inject" && exit 3; }
+eit clean --quick || { echo "ouch unable to remove" && exit 3; }
+eit vacuum --quick || { echo "ouch unable to remove" && exit 3; }
+
 echo "Yes Yes Yes" | eit commit --quick
 eit push --quick --force
 
@@ -88,6 +79,7 @@ default-repository = $REPOSITORY_NAME
 repository=$REPOSITORY_NAME|$REPOSITORY_DESCRIPTION|file:///sabayon/artifacts
 EOF
 
+
 function cleanup {
   rm -rf $createrepo
   rm -rf $entropysrv
@@ -95,27 +87,7 @@ function cleanup {
 
 trap cleanup EXIT
 
+
 echo "docker run --rm --entrypoint /bin/bash ${docker_env[@]} ${docker_volumes[@]} -ti $DOCKER_IMAGE /sabayon/bin/create_repo.sh"
 
 docker run --rm --entrypoint /bin/bash "${docker_env[@]}" "${docker_volumes[@]}" -ti $DOCKER_IMAGE /sabayon/bin/create_repo.sh || true
-
-if [ -d "$SAB_WORKSPACE/entropy_artifacts/standard" ]; then
-  echo "The Sabayon repository files are in $SAB_WORKSPACE/entropy_artifacts"
-  echo "Now you can upload its content where you want"
-
-  echo ""
-  echo "Here it is the repository file how will look like "
-  echo "(if you plan to upload it to a webserver, modify the URI accordingly)"
-  echo "
-  [$REPOSITORY_NAME]
-  desc = $REPOSITORY_DESCRIPTION
-  repo=file://$SAB_WORKSPACE/entropy_artifacts#bz2
-  enabled = true
-  pkg = file://$SAB_WORKSPACE/entropy_artifacts
-  "
-else
-  echo "Something failed :("
-fi
-
-rm -rf $createrepo
-rm -rf $entropysrv
