Use new eit options

diff --git a/sabayon-createrepo b/sabayon-createrepo
--- a/sabayon-createrepo
+++ b/sabayon-createrepo
@@ -68,8 +68,8 @@ fi
 eit key import \$repo /etc/entropy/mykeys/private.key /etc/entropy/mykeys/key.pub && { eit key sign \$repo || true; } && { echo "=== Repository key imported successfully ==="; }
 
 echo "=== Injecting packages ==="
-echo "Yes" | eit inject \${built_pkgs} || { echo "ouch unable to inject" && exit 3; }
-echo "Yes Yes Yes" | eit commit --quick
+eit inject --quick \${built_pkgs} || { echo "ouch unable to inject" && exit 3; }
+eit commit --quick
 
 echo "=== Pushing built packages locally ==="
 eit push --quick --force
